version: "3.8"
services:
  raspap:
    container_name: raspap
    #image: ghcr.io/raspap/raspap-docker:latest
    build: .
    #ports:
    #  - "8081:8081"
    privileged: true
    network_mode: host
    cgroup: host # uncomment when using an ARM device
    environment:
      - RASPAP_SSID=ChristmasTrain
      - RASPAP_SSID_PASS=Password
      - RASPAP_COUNTRY=CA
      - RASPAP_WEBGUI_USER=admin
      - RASPAP_WEBGUI_PASS=secret
      - RASPAP_WEBGUI_PORT=80
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    restart: unless-stopped
